### ISSUE TITLE
Changes to ~/.tmux.conf

### ISSUE THREAD

**Issue by jar349** [ryanfb/etc#1]
Regarding [this blog entry](https://ryanfb.github.io/etc/2015/10/19/tmux_mouse_mode_on_el_capitan.html) one will now encounter `invalid or unknown command` when following your examples due to changes in command argument format.  See: https://github.com/tmux/tmux/issues/754#issuecomment-297452143 for the necessary changes.

**Comment by ryanfb** [comment]
Thanks!
