### ISSUE TITLE
The technique described in "Going cookie-free with Rails" doesn't clear the session

### ISSUE THREAD

**Issue by goulvench** [ryanfb/etc#105]
In [Going cookie-free with Rails](https://ryanfb.github.io/etc/2021/08/29/going_cookie-free_with_rails.html), the following code is shown:
```ruby
after_action lambda {
  request.session_options[:skip] = !(user_signed_in? || devise_controller?)
}
```
This works for guest users and signed-in users, but after signing out the contents of the flash is shown on every page, and the session cookie remains on the computer.

The following code clears the flash and removes the session cookie after signing out:

```ruby
after_action lambda {
  cookies.delete(Rails.application.config.session_options[:key]) unless user_signed_in?
  request.session_options[:skip] = !(user_signed_in? || devise_controller?)
}
```

There might be a nicer way to get the session cookie name but I'm not familiar with this area of the Rails API.

**Comment by ryanfb** [comment]
Thanks, I've added it to the post!
