### ISSUE TITLE
mac-compiled meshroom doesn't utilize the gpu.

### ISSUE THREAD

**Issue by joncastillo** [ryanfb/etc#25]
The GPU is a GTX980TI connected via an egpu enclosure. This card works fine with other applications like autodesk.

**Comment by ryanfb** [comment]
Does running a meshroom reconstruction end-to-end succeed? It should fail at the depth map estimation step if it can't find an appropriate CUDA device, and feature extraction should optionally use the GPU if it can find it. Both of these should output GPU information with a [`gpuInformationCUDA`](https://github.com/alicevision/AliceVision/blob/master/src/aliceVision/system/gpu.hpp) call - can you look in the logs and post what that says?

**Comment by joncastillo** [comment]
My mistake, it actually does. There are only a few stages where the graphics card is used. I was monitoring for all. Sorry for the late response, didn't see this thread active till I made a mistake clicking the a tab here.

**Comment by ryanfb** [comment]
No problem. See https://github.com/alicevision/AliceVision/issues/481 for the upstream issue on non-optimal GPU utilization.
