### ISSUE TITLE
Build of Meshroom now requires XCode 10?

### ISSUE THREAD

**Issue by kboortz** [ryanfb/etc#38]
Ryan,

Really appreciate you have worked on, and documented, the steps to build Meshroom on macOS!

I'm trying out your description but I am running into some trouble. My steps

1. I verified I have the graphic card support and that I run macOS 10.13.4.
2. I deinstalled and reinstalled brew as it was broken, so it is totally clean.
3. I installed the command line tools and verified I run Xcode 9.4.1.
4. I did the "xcode-select --switch /Library/Developer/CommandLineTools"
5. I verified that I run clang 9.0.1.
6. I did run "brew install ryanfb/alicevision/alicevision"

This is where I run into trouble, the install stops with
```
-- Configuring incomplete, errors occurred!
See also "/tmp/alicevision-20190302-67396-16jt2d7/AliceVision-2.0.0/build/CMakeFiles/CMakeOutput.log".
See also "/tmp/alicevision-20190302-67396-16jt2d7/AliceVision-2.0.0/build/CMakeFiles/CMakeError.log".

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/ryanfb/homebrew-alicevision/issues

Error: Your Xcode (9.4.1) is outdated.
Please update to Xcode 10.1 (or delete it).
Xcode can be updated from the App Store.

Error: A newer Command Line Tools release is available.
Update them from Software Update in the App Store.
```
Thankful for any guidance,

kent

**Comment by ryanfb** [comment]
With CUDA 10.1 installed, you should be fine with using Xcode 10.1 now. I've updated the guide to reflect this in 4bff9c8cc5c92f92e58ebd1a9382048a24878596: https://ryanfb.github.io/etc/2018/08/17/alicevision_and_meshroom_on_mac_os_x.html
